name = "blackpill_stm32f401_keyled_demo"
description = "Key/LED demo for BlackPill STM32F401"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "embedded", "demo", "blackpill", "stm32f401"]

project-files = ["gnat/blackpill_stm32f401_keyled_demo.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_stm32f401_gpio = "*"
light_blackpill_stm32f401 = "*"
